import React, { Component, Fragment } from "react";
import { 
    Box,
    Card,
    Grid,
    Container,
    } from "@material-ui/core";


import { withStyles } from "@material-ui/styles";
const guidance= [
    {
      
      description: 'The One Health Monitoring Tool (OHMT) is built around drivers to institutionalize and operationalize One Health. It is a tool that is used to assess progress made, and identify gaps on OH implementation at the local, national, and regional levels. The tool is intended to be used for collecting semi-quantitative data, that is fed into a digital system which generates visuals allowing for a comprehensive overview of operational gaps. The tool also serves as toolkit to facilitate users identify existing OH tools, guidelines, initiatives, and other existing resources promoting multisectoral and multidisciplinary collaboration that can be used for reference to address identified OH gaps.',
      
      title: 'Purpose',
      
    },
    {

      description: 'The tool is composed of sixfour specific components. 1- User guidance 2- Definition of key terms 3- Reference guide (Tool kit) 4- Assessment of dDomains (Governance; Implementation and Performance) 5- Result of the assessment 6- Report of the assessment Domain (2): A group of categories that relate to a broad sub-category of actions intended to improve One Health institutionalization and operationalization. Category (6): Areas of focus generated in relation to circumstances that form the backdrop for each of the given domain. Sub-Category (26): Specific areas which enable the self-assessment to evaluate achievements against specific attributes related to each category.',
     
      title: "Structure of the tool" ,
     
    },
    {
      
      
      description: "The individual (s) conducting the self-assessment assigns a score (1- 4) into the OHMT scoring grid to each of the 26 sub-categories. The scoring scale prompts specific question(s) related to each statement that need to be read and understood prior to selection of the appropriate score. The scores are automatically calculated and visuals (spider web diagram, bar graphs etc.) depicting operational strengths and gaps for each domain are automatically generated. The outputs generated by the OHMT system will be the basis from which guidance for improvements are proposed in reference to the toolkit. 1- No initiative is in place for implementing OH 2- Plans are in place to develop initiatives that will improve OH 3- OH implementation is ongoing, but initiatives/activities are not yet endorsed by relevant competent authorities 4- OH implementation is ongoing, and initiatives/activities are endorsed by relevant competent authorities",
      
      title: 'Scoring scale and criteria’s to be used ',
      
    },
    
  ];

class Dashboard1 extends Component {
  state = guidance;

  render() {
   

    return (
      <Fragment>
  
      <Container maxWidth={false}>
        {/* <Toolbar /> */}
        <Box mt={3} mb={3}>
          <Grid
            container
            spacing={1}
          >
            {this.state.map((p) => (
              <Grid
                item
                key={p.id}
                lg={12}
                md={12}
                xs={12}
              >
        <Card elevation={0} className="upgrade-card bg-light-primary p-sm-24">
            <h2 className="text-muted m-0 py-1" >{p.title}</h2>
        <p className="text-muted text-align-left m-0 py-4" style={{ textAlign: "left" }}>
          {p.description}
        </p>
       
      </Card>
              </Grid>
            ))}
          </Grid>
        </Box>
       
      </Container>
   
           
      </Fragment>
    );
  }
}

export default withStyles({}, { withTheme: true })(Dashboard1);